security:
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      scope: read, write
      auto-approve-scopes: .*
    authorization:
      check-token-access: isAuthenticated()
server:
  port: 8081
  servlet:
    context-path: /uaa
spring:
  security:
    user: 
      name: user123
      password: pass1234
      roles: USER
logging:
  level:
    org.springframework.security: DEBUG