spring:
  oauth2:
    client:
      client-id: demo
      client-secret: demo
    resource:
      token-info-uri: ${auth-server:http://localhost:8081/uaa}/oauth/check_token
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    
server:
  port: 8082
  