security:
  basic:
    enabled: false
  oauth2:
    authorization:
      check-token-access: isAuthenticated()

security.oauth2:
    client:
      client-id: java-client
      client-secret: demo
      auto-approve-scopes: .*
      authorized-grant-type: authorization_code,refresh_token,password
      scope: read, write

# ---

# security.oauth2:
#     client:
#       client-id: go-oauth2-client
#       client-secret: go-oauth2-client-secret
#       auto-approve-scopes: .*
#       authorized-grant-type: authorization_code,refresh_token,password
#       scope: read, write
# ---

server:
  port: 8081
  servlet:
    context-path: /uaa
spring:
  security:
    user: 
      name: user123
      password: pass1234
      roles: USER
logging:
  level:
    org.springframework.security: DEBUG
    