# Resolves views selected for rendering by @Controllers to .jsp resources in the /WEB-INF/views directory
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  port: 9090
  servlet:
    context-path: /simple-web-app